# Generated by Django 4.1.1 on 2022-09-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_autor_topico_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='conteudo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
