# Generated by Django 4.1.1 on 2022-09-17 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topico_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='horaPostagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
