# Generated by Django 4.1.1 on 2022-09-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topico_horapostagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20)),
                ('horaPostagem', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.CharField(max_length=500)),
            ],
        ),
    ]
