# Generated by Django 4.1.1 on 2022-09-17 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='topico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.topico'),
        ),
    ]
